GET http://localhost:3000/products


###
GET http://localhost:3000/products/5


### 


POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 3",
    "price": 100
}

###
PATCH  http://localhost:3000/products/2
Content-Type: application/json

{
    "name": "Productoo",
    "price": 100
}

###
DELETE http://localhost:3000/products/3


###

POST http://localhost:3000/stock-inputs
Content-Type: application/json

{
    "productId": 5,
    "quantity": 10,
    "date": "2021-01-01"
}